# Site settings
title: Lucy Yu
email: lucyyu1996@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer science student at UWaterloo. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lucyyu.me" # the base hostname & protocol for your site
github_username:  lucyyu24
linkedin_username:  lucyu
soundcloud_username: lucy_yu

# Build settings
markdown: kramdown
