# Site settings
title: Zanny
email: lucyyu1996@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ouroboros.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://zanny.net" # the base hostname & protocol for your site
github_username:  lucyyu24
linkedin_username:  zannyxy
soundcloud_username: lucyu
twitter_username: zannyxy

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
