# Site settings
title: Jiaao
description: > # this means to ignore newlines until "baseurl:"
  Of earth and stars.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jiaaomusic.com" # the base hostname & protocol for your site
soundcloud_username: jiaaomusic
instagram_username: jiaaomusic
# social icons: https://www.iconfinder.com/iconsets/social-media-iconez

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/blog/page:num/"
